# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='bgn_to_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.TextField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_sign',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_to_bgn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
